name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
autolabeler:
  - label: "major"
    title:
      - '/^[a-z]+\(MIKE-\d+\)!:/'
    body:
      - "/BREAKING CHANGE/i"
  - label: "minor"
    branch:
      - '/^feat(ure)?\//'
    title:
      - '/^feat\(MIKE-\d+\):/'
  - label: "fix"
    branch:
      - '/^fix\//'
      - '/^bug\//'
    title:
      - '/^fix\(MIKE-\d+\):/'
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
      - "fix"
  default: patch
template: |
  ## Changes

  $CHANGES
